name: Mod Support Request
description: Request support for a specific mod
title: "[Mod Support Request] EXAMPLE MOD"
labels: ["mod request"]
body:
  - type: markdown
    attributes:
      value: |
        Please check for duplicated first and only reuqest one mod a issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add any context or screenshots about the requested mod below.
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Link to the mod page
      description: Please provide a URL to the mod page.
      placeholder: "Example: https://www.curseforge.com/minecraft/texture-packs/darkmode"
    validations:
      required: true

  - type: dropdown
    id: versions
    attributes:
      label: Game versions
      description: What game versions should be supported? Select all applicable game versions.
      multiple: true
      options:
        - 1.20
        - 1.19
        - 1.18
        - 1.17
        - 1.16
        - 1.15
        - 1.14
        - 1.13
        - 1.12
        - 1.11
        - 1.10
        - 1.9
        - 1.8
        - 1.7
        - 1.6
        - any
    validations:
      required: true

  - type: dropdown
    id: modloaders
    attributes:
      label: Modloaders
      description: What modloader is the mod using? Select all applicable modloaders.
      multiple: true
      options:
        - Fabric
        - Forge
        - Quilt
        - Other
    validations:
      required: true
